"""Add stablecoin table

Revision ID: ac37a13e26dd
Revises: 
Create Date: 2023-11-25 11:02:46.963420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac37a13e26dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stablecoin',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('balance', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stablecoin'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stablecoin')
    # ### end Alembic commands ###
